/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_retech_richbook_reader_BookReaderJni */

#ifndef _Included_com_retech_richbook_reader_BookReaderJni
#define _Included_com_retech_richbook_reader_BookReaderJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_retech_richbook_reader_BookReaderJni
 * Method:    initGlobalSettings
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_com_retech_richbook_reader_BookReaderJni_initGlobalSettings
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     com_retech_richbook_reader_BookReaderJni
 * Method:    setListeners
 * Signature: (Ljava/lang/Object;Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_retech_richbook_reader_BookReaderJni_setListeners
  (JNIEnv *, jclass, jobject, jobject);

/*
 * Class:     com_retech_richbook_reader_BookReaderJni
 * Method:    drawBookContent
 * Signature: ([ILjava/lang/Object;Z)V
 */
JNIEXPORT void JNICALL Java_com_retech_richbook_reader_BookReaderJni_drawBookContent
  (JNIEnv *, jclass, jintArray, jobject, jboolean);

/*
 * Class:     com_retech_richbook_reader_BookReaderJni
 * Method:    loadBook
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_retech_richbook_reader_BookReaderJni_loadBook
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_retech_richbook_reader_BookReaderJni
 * Method:    nextPage
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_retech_richbook_reader_BookReaderJni_nextPage
  (JNIEnv *, jclass);

/*
 * Class:     com_retech_richbook_reader_BookReaderJni
 * Method:    lastPage
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_retech_richbook_reader_BookReaderJni_lastPage
  (JNIEnv *, jclass);

/*
 * Class:     com_retech_richbook_reader_BookReaderJni
 * Method:    goToPage
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_retech_richbook_reader_BookReaderJni_goToPage
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_retech_richbook_reader_BookReaderJni
 * Method:    setFontSize
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_retech_richbook_reader_BookReaderJni_setFontSize
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_retech_richbook_reader_BookReaderJni
 * Method:    isCurPosVisible
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_retech_richbook_reader_BookReaderJni_isCurPosVisible
  (JNIEnv *, jclass);

/*
 * Class:     com_retech_richbook_reader_BookReaderJni
 * Method:    dragComment
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_retech_richbook_reader_BookReaderJni_dragComment
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     com_retech_richbook_reader_BookReaderJni
 * Method:    selSentence
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_retech_richbook_reader_BookReaderJni_selSentence
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     com_retech_richbook_reader_BookReaderJni
 * Method:    dragSentence
 * Signature: (FF)Z
 */
JNIEXPORT jboolean JNICALL Java_com_retech_richbook_reader_BookReaderJni_dragSentence
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     com_retech_richbook_reader_BookReaderJni
 * Method:    onClick
 * Signature: (FF)V
 */
JNIEXPORT void JNICALL Java_com_retech_richbook_reader_BookReaderJni_onClick
  (JNIEnv *, jclass, jfloat, jfloat);

/*
 * Class:     com_retech_richbook_reader_BookReaderJni
 * Method:    onTouchMove
 * Signature: (FF[I)V
 */
JNIEXPORT void JNICALL Java_com_retech_richbook_reader_BookReaderJni_onTouchMove
  (JNIEnv *, jclass, jfloat, jfloat, jintArray);

/*
 * Class:     com_retech_richbook_reader_BookReaderJni
 * Method:    removeBookmark
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_retech_richbook_reader_BookReaderJni_removeBookmark
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
